// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knurxhdxkoaxipwwpjhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtudXJ4aGR4a29heGlwd3dwamhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyOTUyNDUsImV4cCI6MjA1Mzg3MTI0NX0.3f3YscxnPqf02Zopj-jwxmc1VpG6w5ZG_VDVLezyznk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);